### ISSUE TITLE
Introduce EIP-7702 (Set EOA account code)

### ISSUE THREAD

**Issue by Mdaiki0730** [kaiachain/kaia#106]
**Is your request related to a problem? Please describe.**
Kaia has an account abstraction in the form of ERC-4337. 
We can receive the benefits of AA through this, but if you already have an EOA account, you will need to create a new contract account and transfer assets.

**Describe the solution you'd like**
Introducing EIP-7702 can solve this problem.
EIP-7702 allows you to treat an EOA like a contract account by setting a contract in the code field of the EOA.
A new `SET_CODE_TX_TYPE` is going to be defined, which will work as follows:
![EIP7702_detail_process](https://github.com/user-attachments/assets/19f07b06-2853-4500-9d74-0bd617183a2e)

**Describe alternatives you've considered**
- EIP-3074
  - EIP-7702 was additionally proposed as an alternative.
- RIP-7560
  - Because this is a proposal for Rollup, it seems a bit difficult to introduce it to L1 right away.

**Additional context**
The following changes are expected:

##### Add Objects
- Add SetCodeTxType, which implements TxInternalData. This will be treated as the EthTypedTransaction.
- Define an AuthorizationList([]Authorization) for the authorization tuple.

##### Changes
- /api
  - Change the interface of api to correspond to `SetCodeTxType`
- /blockchain
  - state_transition
    - Add the main code for adding set code and authority to `StateTransition.TransitionDb`
  - types/tx_internal_data
    - Add `TxTypeSetCode`
    - Extende the `StateDB` interface (for validation)
  - tx_pool
    - There may be changes to `validateTx`
  - state/statedb
    - Implement `ResolveCode` in `StateDB`(also resolveStateObject)
  - vm
    - Add 7702 to eips in VM
    - Changed `GetCode` to `ResolveCode` in evm and instructions (If code is requested)
    - Updated interface of `StateDB`
    - Call `enable7702` in jump_table
    - Define gas around EIP7702 in `operations_acl`
- /params
  - Define of gas fee for authorization

**Comment by Mdaiki0730** [comment]
We have found some additional changes that we need to make.
#### Points
- Since [EOA](https://docs.kaia.io/learn/accounts/#externally-owned-accounts-eoas-) does not have a code hash field, how do we retain the EOA after the setcode?
- A change needs to be made to Kaia's Account RPC API related to setcode.

**Comment by Mdaiki0730** [comment]
@kaiachain/core
Regarding how to setcode the EOA, @blukat29  gave me two suggestions for how EOA should retain the code:
1. Change from [EOA](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/account.go#L37) to [SCA](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/account.go#L38) when the code is set
2. Define a new [AccountType](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/account.go#L33) and switch to that when the code is set (such as ExternallyOwnedAccountHasCodeType)

In my opinion, option 1 is ideal.
The reason is that the purpose of introducing EIP7702 is to set code in the existing EOA and make the EOA control programmable, which is consistent with the nature of SCA, which is control by code.

However, I am concerned about the following points when the EOA becomes an SCA. In some cases, it may be necessary to consider option 2. Could you please let me know your opinions?
- We hope that EOA who has become an SCA can start new transactions, but is it possible to relax the [conditions under which an SCA cannot start new transactions](https://docs.kaia.io/learn/accounts/#smart-contract-accounts-scas-)? Also, are there any possible issues that could be caused by relaxing it?
  - The possibility that this issue could be caused is being considered
    - https://kaia-foundation.atlassian.net/wiki/spaces/CJIL/pages/47513889/Seminar+2024-10-21+What+is+EIP-7702
- If there is any benefit currently received from a clear separation between EOA and SCA, it will be gone. What benefit do we currently get?

**Comment by blukat29** [comment]
There is another option.

3. Allow the EOA have additional "optional RLP" fields 

Adding optional RLP fields allows legacy structs keep its RLP encoding while new structs can attach new fields. e.g. https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/block.go#L68-L69

This way we can keep the existing EOA/SCA separation that has existed for whatever reason. But if we keep the SetCode'd account as EOA type, we may need to modify some conditions such as IsProgramAccount.

The EOA/SCA separation affects how some transaction types behave (e.g. SmartContractExecution can only target an EOA). I personally don't think that the explicit separation (type byte) is better than implicit separation (codehash == 0x0), but they are already in place.

**Comment by Mdaiki0730** [comment]
> @kaiachain/core
> Regarding how to setcode the EOA, @blukat29  gave me two suggestions for how EOA should retain the code:
> 1. Change from [EOA](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/account.go#L37) to [SCA](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/account.go#L37) at the time of set code 
> 2. Define a new [AccountType](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/account.go#L33) and switch to that when the code is set (such as ExternallyOwnedAccountHasCodeType)
> 
> In my opinion, option 1 is ideal.
> The reason is that the purpose of introducing EIP7702 is to set code in the existing EOA and make the EOA control programmable, which is consistent with the nature of SCA, which is control by code.
> 
> However, I am concerned about the following points regarding the change from EOA to SCA. In some cases, we may need to consider a new type. Could you please let me know your opinions.
> - We hope that new transactions will continue to be able to be started. Is it possible to relax the [condition that prevents new transactions](https://docs.kaia.io/learn/accounts/#smart-contract-accounts-scas-) from being started? Also, are there any possible issues that could be caused by relaxing it?
>   - The possibility that this issue could be caused is being considered
>   - https://github.com/ethereum/EIPs/blob/9ab44b9534a848a21946d2afe9591767cd1522af/EIPS/eip-7702.md#setting-code-as-txorigin
> - If there is any benefit currently received from a clear separation between EOA and SCA, it will be gone. What benefit do we currently get?

I accidentally deleted my comment so I'll restore it. I'm sorry.

**Comment by Mdaiki0730** [comment]
On reflection, changing the Type doesn't seem like a good idea since it affects the address prefix.
Option 3 may be the most realistic approach.
As we make some changes, such as IsProgramAccount, we need to clearly define how we view setcoded EOA.

> I also assume, that’s obvious that there are numerous assertions that will become faulty via isContract, like [this 5](https://github.com/Instadapp/aave-protocol-v2/blob/672c3b003840ad29b25ba738ede2076d2b36820f/contracts/misc/WalletBalanceProvider.sol#L35) ? Such checks, if checking for isContract==true, will result fault assertions that account cannot send auxiliary transaction while it can.
> https://ethereum-magicians.org/t/eip-7702-set-eoa-account-code/19923/258

> This one might not be as big of a deal, because OZ’s isContract function already had some noteable workarounds like contracts in construction, counterfactual addresses, etc and thus was already unreliable.
> https://ethereum-magicians.org/t/eip-7702-set-eoa-account-code/19923/260

In Ethereum, there was a debate about whether it was OK to return true for isContract for a set coded EOA, and since this has already been broken, it is considered not to be a big problem.
Can we think of the Kaia ecosystem in the same way?

**Comment by blukat29** [comment]
> On reflection, changing the Type doesn't seem like a good idea since it affects the address prefix. Option 3 may be the most realistic approach.

I agree that type change is unrealistic. But let me correct that the account type prefix is NOT on the address, it's inside the StateDB's leaf node. It only affects the Merkle Hash (i.e. header.stateRoot).

---

The `isContract` debate is specifically about the OpenZeppelin's way of determining a contract account in Solidity (https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.6/contracts/utils/Address.sol) that probably use `EXTCODE*` opcodes.

The thing with `isProgramAccount` is in the EVM implementation https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/vm/evm.go#L283-L289 that decides whether the EVM will execute the bytecode or not.

**Comment by Mdaiki0730** [comment]
## Consideration
Treating EOA as a ProgramAccount will affect the following callers of GetProgramAccount:
https://github.com/search?q=repo%3Akaiachain%2Fkaia%20GetProgramAccount&type=code

In this case, the objectives are separated into two:
1. Calling GetProgramAccount to treat Account as a ProgramAccount
2. If it is SCA (ProgramAccount), an error is returned

1 is not a big problem because the purpose is only to obtain the ProgramAccount, but in the case of 2, the EOA Type needs to be retained even after it is set, so a correction is required.

## New Changes
Taking the above issues into consideration, I propose the following changes.

- /blockchain
  - types/account
    - external_owned_account
      - Add rlp optional field (StorageRoot, CodeHash, CodeInfo)
        - https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/smart_contract_account.go#L44-L46
      - Add a method to implement ProgramAccount like SCA
        - https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/smart_contract_account.go#L224-L250
        - https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/smart_contract_account.go#L150-L156
        - https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/types/account/smart_contract_account.go#L114-L218
  - types
    - Change the SCA decision in the following method: (IsProgramAccount == true) to (AccountType == SCA)
      - FeeDelegatedValueTransfer.ValidateMutableValue
      - FeeDelegatedValueTransferMemo.ValidateMutableValue
      - FeeDelegatedValueTransferMemoWithRatio.ValidateMutableValue
      - FeeDelegatedValueTransferWithRatio.ValidateMutableValue
      - ValueTransfer.ValidateMutableValue
      - ValueTransferMemo.ValidateMutableValue
  - state_transition
    - In addition to [the ethereum setcode](https://github.com/ethereum/go-ethereum/pull/30078/files#diff-8c398ef0a79f97ba6d497a99247a815b3a51918de9e16954215b6073f907c92eR467-R513) procedure, we must call [GetOrNewStateObject](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/state/statedb.go#L677) before calling [SetCode](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/state/statedb.go#L467). Because if the stateObject of the target address does not exist when SetCode is executed, the [stateObject is created as a SmartContractAccountType](https://github.com/kaiachain/kaia/blob/de624511032d645a5bdcc40b6e3dde24b2ea44af/blockchain/state/statedb.go#L686-L696). We need to create it as an EOA in advance.

**Comment by shiki-tak** [comment]
@Mdaiki0730 @blukat29 
I added a CodeHash field to the EOA, and as a test, prepared an EOA with CodeHash in genesis and started the chain.
After that, when I checked the account information, the AccountType was 2.

```
> kaia.getAccount("9fdda5cee9e2482eb93716b98310068da9914e7d")
{
  accType: 2,
  account: {
    balance: "0x446c3b15f9926687d2c40534fdb564000000000000",
    codeHash: "I2hB6mVLDxjoPpNLoPabSrIV8Lb/vu4oh5fOZ8ia6iU=",
    humanReadable: false,
    key: {
      key: {},
      keyType: 3
    },
    nonce: 0,
    storageRoot: "0x01f9e62d19297f681ea2208de1fec6c67ed86a26e55dbf4b27a1b0881060507b"
  }
}
```

This is because SetCode is called at the following point based on the genesis data.

https://github.com/kaiachain/kaia/blob/feat/eip-7702/blockchain/genesis.go#L313

The current implementation plan assumes that SetCode will be called only when tx is called.
- Consider an implementation that assumes that the genesis EOA will include Code
- Do not consider adding such an EOA to genesis (SetCode will only be called through tx)

Any other opinions?

**Comment by blukat29** [comment]
If we limit the discussion into Genesis only, The GenesisAlloc with nonempty `Code` is considered a contract account. There is no way to specify "EOA with code" in the Genesis. I think that happened here, so the accType=2 (SCA).

If we only think about Mainnet, "Do not consider adding such an EOA to genesis (SetCode will only be called through tx)" should suffice. But for the sake of easier testing, we may have a option that "allows genesis EOA to have Code".

e.g. (any better suggestions are welcome)
```go
type GenesisAccount struct {
	Code       []byte                      `json:"code,omitempty"`
	Storage    map[common.Hash]common.Hash `json:"storage,omitempty"`
	Balance    *big.Int                    `json:"balance" gencodec:"required"`
	Nonce      uint64                      `json:"nonce,omitempty"`
    ForceEOA bool                         `json:"forceEoa,omitempty"` // for tests
	PrivateKey []byte                      `json:"secretKey,omitempty"` // for tests
}
```

**Comment by shiki-tak** [comment]
If I am allowed to add fields to the GenesisAccount struct for testing purposes, I think your suggestion is so good.

I'll try adding `codeHash[]byte` directly rather than your suggestion of `ForceEOA bool`.

@Mdaiki0730 
If SetCode is only called through tx, I don't think there is any need to implement anything additional for SetCode. What do you think?

**Comment by blukat29** [comment]
@shiki-tak Absolutely! there is already a "for tests" field after all.

**Comment by Mdaiki0730** [comment]
> If SetCode is only called through tx, I don't think there is any need to implement anything additional for SetCode. What do you think?

When SetCode is sent from SetCodeTx to EOA, if the account does not exist in the state, an object will be created as SCA.
To avoid this, how about creating a separate SetCode for EOA?

**Comment by shiki-tak** [comment]
What about adding an EOA with a value set in the CodeHash to the chain without limit the discussion to Genesis? 
The current implementation is expected to setCode on the EOA only when the EOA executes Tx.

If it is possible to set the EOA code at any time other than when executing Tx, it will be necessary to determine whether the account is EOA or SCA without looking at the AccountType. Is this possible?

**Comment by Mdaiki0730** [comment]
KIP-228 (EIP-7702) was added to dev via #172, which bundled the related PRs.
This issue can be closed. Thank you all!!!
