### ISSUE TITLE
How to prun klatyn data

### ISSUE THREAD

**Issue by zhy827827** [kaiachain/kaia#156]
Klatyn's data is getting bigger and bigger, now reaching 5T, which is unacceptable for full nodes!

I added configuration on Ken.conf, but I still can't prun the data
```
KLAYTN_STATE_LIVE_PRUNING="ture"
KLAYTN_STATE_LIVE_PRUNING_RETENTION=90000
```

**Comment by blukat29** [comment]
Hello, you can indeed save disk space using state live pruning, but there is a caveat. If you want to switch to pruning mode, you have to restart from the genesis or start from a pruned chaindata. Read more on https://docs.kaia.io/misc/operation/node-pruning/.

Also note that in `kend.conf` file, you must modify the `ADDITIONAL` variable e.g.
```
ADDITIONAL="--state.live-pruning"
```
variables in kend.conf are not environment variables.

**Comment by zhy827827** [comment]
thank you~~
