### ISSUE TITLE
v1.0.0 not buildable for docker

### ISSUE THREAD

**Issue by jun0tpyrc** [kaiachain/kaia#4]
v1.0.0 not buildable for docker

**Comment by blukat29** [comment]
Hello @jun0tpyrc. kaia v1.0.0 docker image is not yet available on Docker Hub. I anticipate to provide it from v1.0.1. At the moment, you can build the image on your own with following command:

```
docker build -t kaiachain/kaia:latest .
```

Please tell me if you encounter any problem.

**Comment by jun0tpyrc** [comment]
> Hello @jun0tpyrc. kaia v1.0.0 docker image is not yet available on Docker Hub. I anticipate to provide it from v1.0.1. At the moment, you can build the image on your own with following command:
> 
> ```
> docker build -t kaiachain/kaia:latest .
> ```
> 
> Please tell me if you encounter any problem.

```

 > [builder 4/6] RUN --mount=type=cache,target=/go/pkg/mod go mod download -x:
#11 0.314 go: errors parsing go.mod:
#11 0.314 /go/src/github.com/klaytn/klaytn/go.mod:3: invalid go version '1.22.1': must match format 1.23
```
keep hitting similar error for 
DOCKER_BUILDKIT=1 docker build . -t XXXXX/kaia:v1.0.0 --no-cache

also doesn't look working if really pump  thing inside manually

**Comment by blukat29** [comment]
@jun0tpyrc Can you try after `docker pull klaytn/build_base:latest`? It looks like the build_base image's Go version is lower than required 1.22.1. The docker build relies on the klaytn/build_base as stated in our Dockerfile.

**Comment by yoomee1313** [comment]
v1.0.1 has been released. Release note: https://github.com/kaiachain/kaia/releases/tag/v1.0.1. You can find the information for the docker container here. If anything needed, please reopen the issue.
