### ISSUE TITLE
en memory increase

### ISSUE THREAD

**Issue by yoomee1313** [kaiachain/kaia#75]
**Describe the bug**
There's an issue reported that EN memory is keep increasing.
![image](https://github.com/user-attachments/assets/73d60de1-c2bc-4b5d-b01f-9a2f49ec34d1)

**How to reproduce**
Call `debug_traceBlockByNumberRange` for the latest 10 blocks once every 10 seconds.
But it seems that `debug_traceBlockByNumber` also can reproduce the problem.

**Expected memory usage**
The memory usage should be stable. The binary version of the next screenshot is kaia-v1.0.2 + #73, #74.
![image](https://github.com/user-attachments/assets/db795eb8-87bf-4846-a9ce-f9269cdf0e31)

**Comment by calebcall** [comment]
We are also seeing this same memory growth issue.  It'll consume up to the system limit and then OOM.  We originally had our node on a 64Gb system and saw OOM errors, moved to a 128Gb system and the errors continued (just longer between)
![Screenshot 2024-08-24 at 10 51 29 AM](https://github.com/user-attachments/assets/ea99b7ea-926e-4850-9855-e61a6e6f3adb)

**Comment by yoomee1313** [comment]
Yes, we confirmed that there was a memory leak, and by applying the #73, #74, we can see that the memory is stabilized(expected memory usage). Debug trace API is called periodically, isn't it? It might be good to try applying the above changes.

**Comment by yoomee1313** [comment]
You can use https://github.com/kaiachain/kaia/tree/oom-fix branch. Or if you want a binary, please let us know.
