### ISSUE TITLE
v1.0.0 does not provide kend binary

### ISSUE THREAD

**Issue by BomaxChen** [kaiachain/kaia#9]
kaia v1.0.0 does not provide the kend binary. Will the kend binary no longer be provided in the future? We are currently using kend to run the fullnode

**Comment by blukat29** [comment]
Hello @BomaxChen. You can use the existing kend script unchanged. We are planning to resume providing kend tar.gz package and rpm packages from the v1.0.1 which would contain the Mainnet hardfork configuration.

**Comment by yoomee1313** [comment]
v1.0.1 has been release. Release note: https://github.com/kaiachain/kaia/releases/tag/v1.0.1. If anything needed, please reopen the issue.
